version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - npm install express serverless-http
      - npm install body-parser
  build:
    commands:
      - serverless deploy 
artifacts:
  files:
    - serverless.yml
    - serverlesshelloworld.zip
